import Head from 'next/head'


export default function Home() {
  console.log(process.env);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Delivery service!</a>
        </h1>
        <p className="description">
         Development
        </p>
      </main>

    </div>
  )
}